import { BaseAgent } from './BaseAgent.js';

export class FormatterAgent extends BaseAgent {
  constructor() {
    super('FormatterAgent', 'Markdown and Document Layout Coordinator');
  }

  async receiveMessage(sender, message, payload) {
    if (message !== 'FORMAT_STUDY_MATERIAL') {
      throw new Error(`Unsupported message command: ${message}`);
    }

    const { videoTitle, youtubeUrl, summary, keyConcepts, quiz, flashcards } = payload;

    // We can compile the study guide using a robust, clean Markdown template.
    let markdown = `# Study Guide: ${videoTitle}\n`;
    
    if (youtubeUrl) {
      markdown += `**Source Video:** [Watch on YouTube](${youtubeUrl})\n`;
    }
    markdown += `*Generated by Multi-Agent AI Study Assistant on ${new Date().toLocaleDateString()}*\n\n---\n\n`;

    // 1. Summaries
    markdown += `## 📝 Section-wise Study Notes\n\n`;
    if (summary && summary.length > 0) {
      summary.forEach(section => {
        markdown += `### 🔸 ${section.sectionTitle}\n`;
        if (section.bullets && section.bullets.length > 0) {
          section.bullets.forEach(bullet => {
            markdown += `- ${bullet}\n`;
          });
        }
        markdown += `\n`;
      });
    } else {
      markdown += `*No section summaries generated.*\n\n`;
    }

    markdown += `---\n\n`;

    // 2. Key Concepts Table
    markdown += `## 💡 Core Concepts & Terminology\n\n`;
    if (keyConcepts && keyConcepts.length > 0) {
      markdown += `| Concept / Term | Definition / Explanation |\n`;
      markdown += `| :--- | :--- |\n`;
      keyConcepts.forEach(item => {
        // Escape pipeline chars if any to prevent breaking Markdown tables
        const concept = item.concept.replace(/\|/g, '\\|');
        const definition = item.definition.replace(/\|/g, '\\|');
        markdown += `| **${concept}** | ${definition} |\n`;
      });
      markdown += `\n`;
    } else {
      markdown += `*No key concepts identified.*\n\n`;
    }

    markdown += `---\n\n`;

    // 3. Flashcards
    markdown += `## ⚡ Quick-Revision Flashcards\n\n`;
    if (flashcards && flashcards.length > 0) {
      flashcards.forEach((card, index) => {
        markdown += `### Card ${index + 1}\n`;
        markdown += `**Question:** ${card.front}\n\n`;
        markdown += `> **Answer:** ${card.back}\n\n`;
      });
    } else {
      markdown += `*No revision flashcards generated.*\n\n`;
    }

    markdown += `---\n\n`;

    // 4. Practice Quiz
    markdown += `## 🧠 Concept Verification Quiz\n\n`;
    if (quiz && quiz.length > 0) {
      quiz.forEach((q, index) => {
        markdown += `### Q${index + 1}. ${q.question}\n`;
        const optionLabels = ['A', 'B', 'C', 'D'];
        q.options.forEach((opt, oIdx) => {
          const isCorrect = oIdx === q.answerIndex ? ' (Correct Answer)' : '';
          markdown += `- [ ] **${optionLabels[oIdx]}**: ${opt}${isCorrect}\n`;
        });
        markdown += `\n`;
        markdown += `> **Explanation:** ${q.explanation}\n\n`;
      });
    } else {
      markdown += `*No quiz questions generated.*\n\n`;
    }

    markdown += `\n---\n*End of Study Material. Study smart!*`;

    // Simulate minimal processing delay for natural feel
    await new Promise(resolve => setTimeout(resolve, 600));

    return {
      markdown: markdown.trim()
    };
  }
}
